[solax]
# Basis-URL der Solax Cloud API (inkl. Port)
base_url = "https://www.solaxcloud.com:9443"
# Unterst端tzte Werte: "v1" oder "v2"
api_version = "v2"
# Token-ID laut Solax-Dokumentation
api_key = "0123456789abcdef0123456789abcdef"
# Seriennummer (SN) des Wechselrichters
serial_number = "AB1234567890"
# Optional: UID/Plant-ID laut Dokumentation
site_id = "12345"
# Timeout f端r API Requests in Sekunden
timeout = 10

[cantao]
# Adresse der CANTAO-Instanz
base_url = "https://cantao.example.com"
# Zugriffstoken f端r CANTAO
api_token = "cantao-token"
# Prefix, das allen Metriken vorangestellt wird
metric_prefix = "solax"
# Optional: Mapping einzelner Solax-Felder auf CANTAO-Schl端ssel
metric_mapping = { "yieldtoday" = "energy.today", "yieldtotal" = "energy.total" }
